application: hjsleepstats
version: 7
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /*
  script: sleeptracker.app
  login: admin
- url: /_ah/mail/.+
  script: ReceiveMail.app
inbound_services:
- mail

libraries:
- name: jinja2
  version: latest
