# Generated by Django 2.1.1 on 2020-03-23 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('date', models.DateField()),
                ('meal', models.TextField()),
                ('venue', models.TextField()),
                ('yelpUrl', models.TextField()),
                ('food', models.TextField()),
                ('attendee', models.TextField()),
                ('meal_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('date', models.DateField()),
                ('type', models.TextField()),
                ('desc', models.TextField()),
                ('attendee', models.TextField()),
                ('other_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantToTry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yelpUrl', models.TextField()),
                ('venue', models.TextField()),
                ('notes', models.TextField()),
                ('area', models.TextField()),
                ('food', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SleepInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
                ('minutes', models.IntegerField()),
                ('sleepQuality', models.IntegerField()),
            ],
        ),
    ]
